/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package App;


import java.util.Scanner;

public class Prima {

	public static void main(String[] args) {

		
		
		  Scanner scan = new Scanner(System.in);
		  System.out.println("Ingrese edad del conductor: ");
		  
		  while(!scan.hasNextInt()){
		  System.out.println("¡Ingrese valores numéricos solamente!");
		  System.out.println("Ingrese edad del conductor: "); scan.next(); } int edad =
		  scan.nextInt();
		  
		  System.out.println("Ingrese puntos de licencia del coductor: ");
		  while(!scan.hasNextInt()) {
		  System.out.println("¡Ingrese valores numéricos solamente!");
		  System.out.println("Ingrese puntos de licencia del coductor: "); scan.next();
		  } int puntosLicencia = scan.nextInt();
		  
		  scan.close();
		  
		  System.out.println(mainPrimaValue(edad, puntosLicencia));
		 
		 

	}
	

	public static double mainPrimaValue(int age, int licensePoints) {
		
		Conductor driver = new Conductor(age, licensePoints);
		if(driver.getAge() < 18 || driver.getAge() > 90) {
			System.out.println(" Edad incorrecta.");
			return 0;
		}
		
		double factorEdad = Seguro.ageFactor(driver);
		int reduccionConductorSeguro = Seguro.safeDriverReduction(driver);
		
		if(reduccionConductorSeguro == -1) {
			System.out.println("No tiene puntos en la licencia!");
			return 0;
		}
		
		if(reduccionConductorSeguro == 1) {
			System.out.println("Puntos inválidos");
			return 0; 
		}
		
		System.out.println("Calculando Valor Prima a Pagar...");
		double primaPagar = Seguro.calculatePrimaValue(500.0, factorEdad, reduccionConductorSeguro);
		
		System.out.println("El valor calculado es: $" + primaPagar);
		return primaPagar;
	}

}